/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1.Vistas;

import java.awt.BorderLayout;

/**
 *
 * @author Usuario
 */
public class Administracion extends javax.swing.JFrame {

    Trabajadores t = new Trabajadores();
    ReporteClienteMasIngresos c = new ReporteClienteMasIngresos();
    ReporteEmpleadosMasIngresos a = new ReporteEmpleadosMasIngresos();
    ReporteEmpleadosVentas b = new ReporteEmpleadosVentas();
    ReporteProductoIngresosSucursal d = new ReporteProductoIngresosSucursal();
    ReporteProductoMasVendidos e = new ReporteProductoMasVendidos();
    ReporteProductosMasIngresos f = new ReporteProductosMasIngresos();
    ReporteProductosVentasSucursal g = new ReporteProductosVentasSucursal();
    ReporteSucursales h = new ReporteSucursales();
    ReporteVentaSucursal i = new ReporteVentaSucursal();

    public Administracion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        rcliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        rempleadoI = new javax.swing.JMenuItem();
        rempleadoV = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        rsucursalI = new javax.swing.JMenuItem();
        rsucursalV = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        rproductoV = new javax.swing.JMenuItem();
        rprodutoI = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("escritorio"); // NOI18N

        escritorio.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));

        jMenu1.setBackground(new java.awt.Color(0, 51, 51));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Registrar Empleado");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 51, 51));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Reportes");

        rcliente.setText("Reportes Clientes");
        rcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rclienteMouseClicked(evt);
            }
        });
        rcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rclienteActionPerformed(evt);
            }
        });
        jMenu2.add(rcliente);

        jMenu3.setText("Reportes Empleados");

        rempleadoI.setText("Empleados con mas ingresos");
        rempleadoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rempleadoIActionPerformed(evt);
            }
        });
        jMenu3.add(rempleadoI);

        rempleadoV.setText("Empleados con mas ventas");
        rempleadoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rempleadoVActionPerformed(evt);
            }
        });
        jMenu3.add(rempleadoV);

        jMenu2.add(jMenu3);

        jMenu4.setText("Reportes Sucursales");

        rsucursalI.setText("Sucursales con mas ingresos");
        rsucursalI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsucursalIActionPerformed(evt);
            }
        });
        jMenu4.add(rsucursalI);

        rsucursalV.setText("Sucursales con mas ventas");
        rsucursalV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsucursalVActionPerformed(evt);
            }
        });
        jMenu4.add(rsucursalV);

        jMenu2.add(jMenu4);

        jMenu5.setText("Reportes Productos");

        rproductoV.setText("Productos mas vendidos");
        rproductoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rproductoVActionPerformed(evt);
            }
        });
        jMenu5.add(rproductoV);

        rprodutoI.setText("Productos con mas ingresos");
        rprodutoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rprodutoIActionPerformed(evt);
            }
        });
        jMenu5.add(rprodutoI);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu6.setBackground(new java.awt.Color(0, 51, 51));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Salir");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenu6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu6KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // c.setVisible(false);
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(t, BorderLayout.CENTER);
        t.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void rempleadoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rempleadoIActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(a, BorderLayout.CENTER);
        a.show();
    }//GEN-LAST:event_rempleadoIActionPerformed

    private void rsucursalIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsucursalIActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(h, BorderLayout.CENTER);
        h.show();
    }//GEN-LAST:event_rsucursalIActionPerformed

    private void rproductoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rproductoVActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(e, BorderLayout.CENTER);
        e.show();
    }//GEN-LAST:event_rproductoVActionPerformed

    private void rclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rclienteMouseClicked

    }//GEN-LAST:event_rclienteMouseClicked

    private void rclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rclienteActionPerformed
        //t.setVisible(false);
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(c, BorderLayout.CENTER);
        c.show();
    }//GEN-LAST:event_rclienteActionPerformed

    private void rprodutoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rprodutoIActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(f, BorderLayout.CENTER);
        f.show();
    }//GEN-LAST:event_rprodutoIActionPerformed

    private void rempleadoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rempleadoVActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(b, BorderLayout.CENTER);
        b.show();
    }//GEN-LAST:event_rempleadoVActionPerformed

    private void rsucursalVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsucursalVActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        escritorio.add(i, BorderLayout.CENTER);
        i.show();
    }//GEN-LAST:event_rsucursalVActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
       Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem rcliente;
    private javax.swing.JMenuItem rempleadoI;
    private javax.swing.JMenuItem rempleadoV;
    private javax.swing.JMenuItem rproductoV;
    private javax.swing.JMenuItem rprodutoI;
    private javax.swing.JMenuItem rsucursalI;
    private javax.swing.JMenuItem rsucursalV;
    // End of variables declaration//GEN-END:variables
}
