/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.proyecto1.Vistas;

import Entidades.DetalleVenta;
import Entidades.Producto;
import Entidades.ProductoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ReporteProductoMasVendidos extends javax.swing.JInternalFrame {

    ProductoDAO prod = new ProductoDAO();
    Producto p = new Producto();
    DetalleVenta dv = new DetalleVenta();
    DefaultTableModel model = new DefaultTableModel();
    
    public ReporteProductoMasVendidos() {
        initComponents();
        listar();
    }

     void listar() {
        List<Producto> lista = prod.MasVendidos();
        model = (DefaultTableModel) tablaProd.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < lista.size(); i++) {

            ob[0] = lista.get(i).getCodigo();
            ob[1] = lista.get(i).getNombre();
            ob[2] = lista.get(i).getStock();

            model.addRow(ob);
        }
        tablaProd.setModel(model);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaProd.setBackground(new java.awt.Color(153, 153, 153));
        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto", "Nombre ", "Cantidad Vendida"
            }
        ));
        jScrollPane1.setViewportView(tablaProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProd;
    // End of variables declaration//GEN-END:variables
}
